Tribute_Page
faridafaqiri/Tribute-page pull request #1
Opened 2024-05-22 19:30 UTC by faridafaqiri

**This project is about making a tribute page**
In this project I did this thing:
- First of all I follow GITHUB flow.
- I created HTML file and CSS.
- Linked HTML file with CSS file.
- Added linters config.
- I added main tag, h1 and h3, p, img, blockquote tag and some other tags for creating my web page.
- I added some property in CSS file for styling and designing.
 

2024-05-22 22:55 UTC, ahzamir requested changes
### Hi @faridafaqiri 🙋‍♀️,

> Excellent work! You have done a great job implementing the project requirements but your project still misses some of the requirements:

- Your HTML file code is not clean:
- **Check the inline comments below.**

# Status: Required Changes 🔁
Make changes to your code and commit and request for a re-review.

![BbcanBbcan3GIF](https://github.com/faridafaqiri/Tribute-page/assets/96838030/3e62d4ef-6fce-45c2-9fdb-226bb7316c79)


 ## Highlights 🌞
 
🎯 Great Design implemented.
![image](https://github.com/faridafaqiri/Tribute-page/assets/96838030/6478e556-eb6f-4df9-8853-076f01452684)

✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed and completed the Tribute Page project task and all requirements.
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
❌ Your Code is clean
**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

2024-05-22 22:55 UTC, ahzamir commented on tribute.html
Your codes are not alligned correctly and are not clean try to make their spacing right.
- [**Suggession**] - On your HTML file, at the bottom right side of your vscode click on `Spaces`  then click on `Index using spaces`, and then select `2` from there. Then align your components according to the 2 spaces.
- Example:
```
<div>
  <p>...</p>
  <h1>.... </h1>
  <img ... />
</div>
```

2024-05-23 04:24 UTC, faridafaqiri commented on tribute.html
@ahzamir 
Thank you for feedback!
I cleaned my html code.

2024-05-23 12:04 UTC, ahzamir approved these changes
### Hi @faridafaqiri 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
![Screenshot 2024-05-23 005526](https://github.com/faridafaqiri/Tribute-page/assets/96838030/d273b9bb-0ab7-48ab-bcad-0feb693f39b5)

# Status: Approved ✅

There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳
![ExcellentNiceGIF](https://github.com/faridafaqiri/Tribute-page/assets/96838030/ae74c721-e88a-4ad7-a061-b4a2e96e5424)

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Tribute Page project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

2024-05-23 12:17 UTC, faridafaqiri commented
Thank you sir for approving my project.💫

On Thu, May 23, 2024, 4:35 PM Ahmad Zamir Yousufi ***@***.***>
wrote:

> ***@***.**** approved this pull request.
> Hi @faridafaqiri <https://github.com/faridafaqiri> 🙋‍♀️,
>
> Excellent work! 💯 You have done a great job implementing all the project
> requirements. 🥳 Your feature is complete! Congratulations!!!🎊
>
>
>    -
>
>    *[REQUIRED]* Share your project on this GROUP
>    <https://www.facebook.com/groups/kick-startdev>, add a simple Proud
>    Moment text and a screenshot of your project then besides that add your
>    project link at the end of the text as a GitHub Source code reference and
>    post.
>    -
>
>    Share your Project on your LinkedIn account and add a proud moment
>    text on it with a screenshot.
>    -
>
>    Well Done great design Implemented. 🎯🎉👍
>    Screenshot.2024-05-23.005526.png (view on web)
>    <https://github.com/faridafaqiri/Tribute-page/assets/96838030/d273b9bb-0ab7-48ab-bcad-0feb693f39b5>
>
> Status: Approved ✅
>
> There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳
> ExcellentNiceGIF.gif (view on web)
> <https://github.com/faridafaqiri/Tribute-page/assets/96838030/ae74c721-e88a-4ad7-a061-b4a2e96e5424>
> Highlights 🌞
>
> 🎉 Great Design Implemented
> ✔️ Created a professional Repo (You created a repository with your project
> name)
> ✔️ Correct use of Gitflow (You created the development branch and made it
> your default branch, then created and committed your work on your feature
> branch)
> ✔️ Commit messages are meaningful
> ✔️ Setup the linters correctly (You added the correct linters config into
> your project according to the language you used on your code)
> ✔️ No linter errors (All linters checks have been passed 🟢)
> ✔️ You have followed the Tribute Page project task and committed using the
> command line
> ✔️ Created the pull request (From your feature branch to the development
> branch you created a pull request and submitted the pull request link for
> review)
> ✔️ Good PR description (You added a meaningful description to your PR
> about your work and the features you added on this pull request)
>
> *Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or
> comments in the PR thread if something is not 100% clear. Please, remember
> to tag me @ahzamir <https://github.com/ahzamir> in your question so I can
> receive the notification.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/faridafaqiri/Tribute-page/pull/1#pullrequestreview-2073772628>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASM6FFXFUJHLM7JHHZ3ZH6TZDXLPRAVCNFSM6AAAAABIEIRYLOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDANZTG43TENRSHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-05-27 06:39 UTC, merged